version: 2
project_name: eventodb

before:
  hooks:
    - bash -c "cd golang && go mod tidy"

release:
  github:
    owner: "eventodb-hq"
    name: "eventodb"

builds:
  - id: eventodb
    dir: golang
    main: ./cmd/eventodb
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    binary: eventodb

archives:
  - id: default
    ids:
      - eventodb
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
